# Generated by Django 2.2.4 on 2020-09-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_project_app', '0002_auto_20200918_1445'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AlterField(
            model_name='wishes',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='exam_project_app.Register'),
        ),
    ]
